platform :ios, '8.0'

target 'CompareImageLib' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'
  pod 'SDWebImage/GIF'
  pod 'YYWebImage'

end
